### ISSUE TITLE
COW 崩溃，报「panic: authIP should always get IP address」

### ISSUE THREAD

**Issue by glacjay** [cyfdecyf/cow#59]
COW 版本：40cdfbd6ab6ff54dcf129858b78c4251e661eb10
Go 版本：1.1.1 Windows 32-bit
崩溃日志：

C:\Users\chujie\Desktop>D:

D:>cd D:\bin\

D:\bin>D:\bin\cow.exe
2013/07/18 15:25:21 COW proxy address 0.0.0.0:7777, PAC url http://<hostip>:7777/pac
panic: authIP should always get IP address

goroutine 16 [running]:
main.authIP(0x20165230, 0x5, 0x5)
        D:/go/home/src/github.com/cyfdecyf/cow/auth.go:210 +0x86
main.Authenticate(0x200f9c00, 0x200fb960, 0x0, 0x0)
        D:/go/home/src/github.com/cyfdecyf/cow/auth.go:187 +0x12a
main.(_clientConn).serve(0x200f9c00)
        D:/go/home/src/github.com/cyfdecyf/cow/proxy.go:325 +0x40e
created by main.(_Proxy).Serve
        D:/go/home/src/github.com/cyfdecyf/cow/proxy.go:176 +0x4bc

goroutine 1 [chan receive]:
main.main()
        D:/go/home/src/github.com/cyfdecyf/cow/main.go:85 +0x216

goroutine 3 [syscall]:
os/signal.loop()
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init路1
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 8 [sleep]:
time.Sleep(0x30b8a000, 0x346)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/runtime/ztime_windows_386.c:19 +0x39
main.func路011()
        D:/go/home/src/github.com/cyfdecyf/cow/sitestat.go:420 +0x2d
created by main.initSiteStat
        D:/go/home/src/github.com/cyfdecyf/cow/sitestat.go:423 +0x5e

goroutine 9 [sleep]:
time.Sleep(0xd964b800, 0x45)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/runtime/ztime_windows_386.c:19 +0x39
main.func路001()
        D:/go/home/src/github.com/cyfdecyf/cow/pac.go:186 +0x2d
created by main.initPAC
        D:/go/home/src/github.com/cyfdecyf/cow/pac.go:189 +0x27

goroutine 10 [chan receive]:
main.sigHandler()
        D:/go/home/src/github.com/cyfdecyf/cow/main.go:21 +0x10f
created by main.main
        D:/go/home/src/github.com/cyfdecyf/cow/main.go:76 +0x11e

goroutine 13 [sleep]:
time.Sleep(0xfc23ac00, 0x6)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/runtime/ztime_windows_386.c:19 +0x39
main.runEstimateTimeout()
        D:/go/home/src/github.com/cyfdecyf/cow/estimate_timeout.go:100 +0x62
created by main.main
        D:/go/home/src/github.com/cyfdecyf/cow/main.go:78 +0x13a

goroutine 14 [select]:
net.(_ioSrv).ExecIO(0x20159618, 0x2016e520, 0x2010e6c0, 0x0, 0x0, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/net/fd_windows.go:236 +0x664
net.(_netFD).accept(0x2012d080, 0x5bd140, 0x0, 0x0, 0x0, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/net/fd_windows.go:644 +0x325
net.(_TCPListener).AcceptTCP(0x20159638, 0x40fc7c, 0x3ebeb8, 0x40fc7c)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/net/tcpsock_posix.go:229 +0x41
net.(_TCPListener).Accept(0x20159638, 0x201595d8, 0x2016e020, 0x200f9c00, 0x0, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/net/tcpsock_posix.go:239 +0x28
main.(*Proxy).Serve(0x2016e020, 0x200f9ac0)
        D:/go/home/src/github.com/cyfdecyf/cow/proxy.go:167 +0x2b7
created by main.main
        D:/go/home/src/github.com/cyfdecyf/cow/main.go:82 +0x1d7

goroutine 15 [syscall]:
syscall.Syscall6(0x76044e90, 0x5, 0xdc, 0x201652a0, 0x20159550, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/runtime/zsyscall_windows_windows_386.c:97 +0x
49
syscall.GetQueuedCompletionStatus(0xdc, 0x201652a0, 0x20159550, 0x20159548, 0xffffffff, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/syscall/zsyscall_windows_386.go:507 +0x7e
net.(*resultSrv).Run(0x20159610)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/net/fd_windows.go:150 +0x11a
created by net.startServer
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist934530519/go/src/pkg/net/fd_windows.go:285 +0xde

D:\bin>pause
请按任意键继续. . .

**Comment by oscar-c** [comment]
我这边也有类似问题。
cow 0.9.4
rc文件配置如下：
listen = http://0.0.0.0:1085 [公网IP]:1085
proxy = socks5://localhost:1080
proxy = socks5://localhost:1081
logFile = /Users/[我的用户名]/.cow/log
userPasswd = user:pass <--去掉这行则没有问题。
loadBalance = backup

局域网内设备通过mDNS名称（类似于 MyMac.local 这样的形式 ）访问COW的服务的时候会出现这样退出，如果通过IP地址访问则没有这样的问题。
